export const NOTES = [
  { note: 'C', octave: 3, type: 'white', freq: 130.81 },
  { note: 'C#', octave: 3, type: 'black', freq: 138.59 },
  { note: 'D', octave: 3, type: 'white', freq: 146.83 },
  { note: 'D#', octave: 3, type: 'black', freq: 155.56 },
  { note: 'E', octave: 3, type: 'white', freq: 164.81 },
  { note: 'F', octave: 3, type: 'white', freq: 174.61 },
  { note: 'F#', octave: 3, type: 'black', freq: 185.00 },
  { note: 'G', octave: 3, type: 'white', freq: 196.00 },
  { note: 'G#', octave: 3, type: 'black', freq: 207.65 },
  { note: 'A', octave: 3, type: 'white', freq: 220.00 },
  { note: 'A#', octave: 3, type: 'black', freq: 233.08 },
  { note: 'B', octave: 3, type: 'white', freq: 246.94 },
  { note: 'C', octave: 4, type: 'white', freq: 261.63 },
  { note: 'C#', octave: 4, type: 'black', freq: 277.18 },
  { note: 'D', octave: 4, type: 'white', freq: 293.66 },
  { note: 'D#', octave: 4, type: 'black', freq: 311.13 },
  { note: 'E', octave: 4, type: 'white', freq: 329.63 },
  { note: 'F', octave: 4, type: 'white', freq: 349.23 },
  { note: 'F#', octave: 4, type: 'black', freq: 369.99 },
  { note: 'G', octave: 4, type: 'white', freq: 392.00 },
  { note: 'G#', octave: 4, type: 'black', freq: 415.30 },
  { note: 'A', octave: 4, type: 'white', freq: 440.00 },
  { note: 'A#', octave: 4, type: 'black', freq: 466.16 },
  { note: 'B', octave: 4, type: 'white', freq: 493.88 },
  { note: 'C', octave: 5, type: 'white', freq: 523.25 },
  { note: 'C#', octave: 5, type: 'black', freq: 554.37 },
  { note: 'D', octave: 5, type: 'white', freq: 587.33 },
  { note: 'D#', octave: 5, type: 'black', freq: 622.25 },
  { note: 'E', octave: 5, type: 'white', freq: 659.25 },
  { note: 'F', octave: 5, type: 'white', freq: 698.46 },
  { note: 'F#', octave: 5, type: 'black', freq: 739.99 },
  { note: 'G', octave: 5, type: 'white', freq: 783.99 },
  { note: 'G#', octave: 5, type: 'black', freq: 830.61 },
  { note: 'A', octave: 5, type: 'white', freq: 880.00 },
  { note: 'A#', octave: 5, type: 'black', freq: 932.33 },
  { note: 'B', octave: 5, type: 'white', freq: 987.77 },
  { note: 'C', octave: 6, type: 'white', freq: 1046.50 },
];

export const CONFIG = {
  FADE_OUT_DURATION: 0.3,
  NEXT_QUESTION_DELAY: 800, // ms
  GAME_MODE: {
    PRACTICE: 'practice',
    FREE: 'free',
  }
};
